import { Product } from '@/types';

export const additionalProducts: Product[] = [
  // Home Care Products (25 items)
  {
    id: 'surf-excel-liquid',
    name: 'Surf Excel Liquid Detergent',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '1L bottle',
    brand: 'Surf Excel',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'ariel-detergent',
    name: 'Ariel Detergent Powder',
    price: 135.00,
    mrp: 150.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '1kg pack',
    brand: 'Ariel',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'tide-detergent',
    name: 'Tide Detergent Powder',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '1kg pack',
    brand: 'Tide',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'rin-detergent',
    name: 'Rin Detergent Bar',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '150g pack',
    brand: 'Rin',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'comfort-fabric-softener',
    name: 'Comfort Fabric Softener',
    price: 90.00,
    mrp: 100.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Comfort',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'dettol-antiseptic',
    name: 'Dettol Antiseptic Liquid',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '550ml bottle',
    brand: 'Dettol',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'harpic-bathroom-cleaner',
    name: 'Harpic Bathroom Cleaner',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '1L bottle',
    brand: 'Harpic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'lizol-floor-cleaner',
    name: 'Lizol Floor Cleaner',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '975ml bottle',
    brand: 'Lizol',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'mr-muscle-kitchen-cleaner',
    name: 'Mr. Muscle Kitchen Cleaner',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml spray',
    brand: 'Mr. Muscle',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'vim-dishwash-liquid',
    name: 'Vim Dishwash Liquid',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '750ml bottle',
    brand: 'Vim',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'pril-dishwash-liquid',
    name: 'Pril Dishwash Liquid',
    price: 50.00,
    mrp: 60.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '750ml bottle',
    brand: 'Pril',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'sunlight-soap-bar',
    name: 'Sunlight Soap Bar',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Sunlight',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'lifebuoy-soap',
    name: 'Lifebuoy Soap Bar',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Lifebuoy',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'lux-soap',
    name: 'Lux Soap Bar',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Lux',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'dove-soap',
    name: 'Dove Soap Bar',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '100g pack',
    brand: 'Dove',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'pears-soap',
    name: 'Pears Soap Bar',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Pears',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'hamam-soap',
    name: 'Hamam Soap Bar',
    price: 22.00,
    mrp: 28.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Hamam',
    offers: ['Best Price'],
    margin: 6.00,
    inStock: true,
  },
  {
    id: 'santoor-soap',
    name: 'Santoor Soap Bar',
    price: 28.00,
    mrp: 35.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Santoor',
    offers: ['Offer Applicable'],
    margin: 7.00,
    inStock: true,
  },
  {
    id: 'cinthol-soap',
    name: 'Cinthol Soap Bar',
    price: 25.00,
    mrp: 32.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Cinthol',
    offers: ['2 Offers'],
    margin: 7.00,
    inStock: true,
  },
  {
    id: 'mysore-sandal-soap',
    name: 'Mysore Sandal Soap',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Mysore Sandal',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'medimix-soap',
    name: 'Medimix Soap Bar',
    price: 32.00,
    mrp: 38.00,
    discount: 16,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Medimix',
    offers: ['Best Price'],
    margin: 6.00,
    inStock: true,
  },
  {
    id: 'margo-soap',
    name: 'Margo Soap Bar',
    price: 35.00,
    mrp: 42.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Margo',
    offers: ['Offer Applicable'],
    margin: 7.00,
    inStock: true,
  },
  {
    id: 'rexona-soap',
    name: 'Rexona Soap Bar',
    price: 30.00,
    mrp: 36.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Rexona',
    offers: ['2 Offers'],
    margin: 6.00,
    inStock: true,
  },
  {
    id: 'dettol-soap',
    name: 'Dettol Soap Bar',
    price: 28.00,
    mrp: 35.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Dettol',
    offers: ['Offer Applicable'],
    margin: 7.00,
    inStock: true,
  },
  {
    id: 'savlon-soap',
    name: 'Savlon Soap Bar',
    price: 26.00,
    mrp: 33.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '75g pack',
    brand: 'Savlon',
    offers: ['Best Price'],
    margin: 7.00,
    inStock: true,
  },

  // Beverages (25 items)
  {
    id: 'taj-mahal-tea',
    name: 'Taj Mahal Tea Bags',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '100 tea bags',
    brand: 'Taj Mahal',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'red-label-tea',
    name: 'Red Label Tea',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Red Label',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'lipton-tea',
    name: 'Lipton Yellow Label Tea',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Lipton',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'brooke-bond-tea',
    name: 'Brooke Bond Taj Tea',
    price: 80.00,
    mrp: 90.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Brooke Bond',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'wagh-bakri-tea',
    name: 'Wagh Bakri Premium Tea',
    price: 70.00,
    mrp: 80.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Wagh Bakri',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'nestea-iced-tea',
    name: 'Nestea Iced Tea',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '500ml bottle',
    brand: 'Nestea',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'bru-coffee',
    name: 'Bru Coffee',
    price: 95.00,
    mrp: 105.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '200g pack',
    brand: 'Bru',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'nescafe-classic',
    name: 'Nescafe Classic Coffee',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '100g jar',
    brand: 'Nescafe',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'sunrise-coffee',
    name: 'Sunrise Coffee',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '200g pack',
    brand: 'Sunrise',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'continental-coffee',
    name: 'Continental Coffee',
    price: 110.00,
    mrp: 125.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '200g pack',
    brand: 'Continental',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'tropicana-orange-juice',
    name: 'Tropicana Orange Juice',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '1L tetra pack',
    brand: 'Tropicana',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'real-mixed-fruit-juice',
    name: 'Real Mixed Fruit Juice',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '1L tetra pack',
    brand: 'Real',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'minute-maid-apple-juice',
    name: 'Minute Maid Apple Juice',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '1L tetra pack',
    brand: 'Minute Maid',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'coca-cola',
    name: 'Coca Cola Soft Drink',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Coca Cola',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'pepsi-cola',
    name: 'Pepsi Cola Soft Drink',
    price: 32.00,
    mrp: 38.00,
    discount: 16,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Pepsi',
    offers: ['Offer Applicable'],
    margin: 6.00,
    inStock: true,
  },
  {
    id: 'sprite-lemon-lime',
    name: 'Sprite Lemon Lime',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Sprite',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: '7up-lemon-lime',
    name: '7UP Lemon Lime',
    price: 28.00,
    mrp: 33.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: '7UP',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'fanta-orange',
    name: 'Fanta Orange',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Fanta',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'mirinda-orange',
    name: 'Mirinda Orange',
    price: 28.00,
    mrp: 33.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Mirinda',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'thumbs-up-cola',
    name: 'Thumbs Up Cola',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Thumbs Up',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'limca-lemon',
    name: 'Limca Lemon Lime',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Limca',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'red-bull-energy',
    name: 'Red Bull Energy Drink',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250ml can',
    brand: 'Red Bull',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'monster-energy',
    name: 'Monster Energy Drink',
    price: 85.00,
    mrp: 100.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250ml can',
    brand: 'Monster',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'sting-energy',
    name: 'Sting Energy Drink',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250ml bottle',
    brand: 'Sting',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'gatorade-sports-drink',
    name: 'Gatorade Sports Drink',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '500ml bottle',
    brand: 'Gatorade',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'electral-powder',
    name: 'Electral Powder',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '20.5g sachet',
    brand: 'Electral',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'glucose-d-powder',
    name: 'Glucose D Powder',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1546173/pexels-photo-1546173.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '200g pack',
    brand: 'Glucose D',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
]; 