import { Product, Category } from '@/types';
import { additionalProducts } from './additional_products';
import { moreProducts } from './more_products';
import { remainingProducts } from './remaining_products';
import { electronicsProducts } from './electronics_products';

export const categories: Category[] = [
  {
    id: 'homecare',
    name: 'Home care',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&h=300&fit=crop',
    subcategories: ['Cleaning Supplies', 'Laundry', 'Kitchen Care', 'Bathroom Care']
  },
  {
    id: 'beverages',
    name: 'Beverages',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=300&h=300&fit=crop',
    subcategories: ['Tea', 'Coffee', 'Juices', 'Soft Drinks', 'Energy Drinks']
  },
  {
    id: 'personalcare',
    name: 'Personal care',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop',
    subcategories: ['Skincare', 'Haircare', 'Oral Care', 'Bath & Body']
  },
  {
    id: 'ricedals',
    name: 'Rice, Atta & Dals',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop',
    subcategories: ['Rice', 'Wheat & Flour', 'Pulses', 'Grains']
  },
  {
    id: 'packagedfoods',
    name: 'Packaged Foods & Dry Fruits',
    image: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=300&h=300&fit=crop',
    subcategories: ['Biscuits', 'Snacks', 'Dry Fruits', 'Cereals', 'Instant Foods', 'Nuts & Seeds']
  },
  {
    id: 'oilsugar',
    name: 'Oil, Sugar & Masalas',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=300&fit=crop',
    subcategories: ['Cooking Oil', 'Sugar', 'Spices', 'Salt', 'Ghee', 'Masalas', 'Condiments']
  },
  {
    id: 'dailyfresh',
    name: 'Daily Fresh & Frozen',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&h=300&fit=crop',
    subcategories: ['Fresh Vegetables', 'Fresh Fruits', 'Frozen Foods', 'Dairy Products', 'Meat & Fish']
  },
  {
    id: 'kitchenappliances',
    name: 'Kitchen & Home Appliances',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=300&fit=crop',
    subcategories: ['Kitchen Appliances', 'Home Appliances', 'Cookware', 'Small Appliances', 'Kitchen Tools']
  },
  {
    id: 'beauty',
    name: 'Beauty & Cosmetics',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&h=300&fit=crop',
    subcategories: ['Makeup', 'Skincare', 'Fragrances', 'Hair Products', 'Nail Care']
  },
  {
    id: 'babycare',
    name: 'Baby Care & Toys',
    image: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?w=300&h=300&fit=crop',
    subcategories: ['Diapers', 'Baby Food', 'Toys', 'Clothing', 'Care Products']
  },
  {
    id: 'petcare',
    name: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=300&h=300&fit=crop',
    subcategories: ['Pet Food', 'Toys', 'Grooming', 'Accessories', 'Health Care']
  },
  {
    id: 'automotive',
    name: 'Automotive',
    image: 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=300&h=300&fit=crop',
    subcategories: ['Car Care', 'Accessories', 'Tools', 'Oils', 'Spare Parts']
  },
  {
    id: 'sports',
    name: 'Sports & Fitness',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop',
    subcategories: ['Fitness Equipment', 'Sports Gear', 'Activewear', 'Supplements', 'Yoga']
  },
  {
    id: 'books',
    name: 'Books & Stationery',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop',
    subcategories: ['Books', 'Notebooks', 'Pens', 'Art Supplies', 'Office Supplies']
  },
  {
    id: 'garden',
    name: 'Garden & Outdoor',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
    subcategories: ['Plants', 'Garden Tools', 'Outdoor Furniture', 'BBQ', 'Decor']
  },
  {
    id: 'furniture',
    name: 'Furniture & Home',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=300&fit=crop',
    subcategories: ['Living Room', 'Bedroom', 'Kitchen', 'Office', 'Outdoor']
  },
  {
    id: 'restaurantsupplies',
    name: 'Restaurant Supplies & Houseware',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&h=300&fit=crop',
    subcategories: ['Kitchen Equipment', 'Serving Dishes', 'Cleaning Supplies', 'Storage Containers', 'Utensils']
  },
  {
    id: 'itstationary',
    name: 'IT Stationary & Office Furniture',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop',
    subcategories: ['Computers', 'Office Supplies', 'Furniture', 'Electronics', 'Stationery', 'Printers']
  }
];

export const products: Product[] = [
  // Packaged Foods & Dry Fruits (Biscuits, Snacks, etc.)
  {
    id: 'parle-krackjack',
    name: 'Parle Krackjack Sweet & Salty Biscuits',
    price: 9.09,
    mrp: 10.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '56.7 g + 6.3 g',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 0.91,
    inStock: true,
  },
  {
    id: 'parle-monaco',
    name: 'Parle Monaco Biscuit 400 g',
    price: 72.73,
    mrp: 80.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '400g pack',
    brand: 'Parle',
    offers: ['3 Offers'],
    margin: 7.27,
    inStock: true,
  },
  {
    id: 'britannia-goodday',
    name: 'Britannia Good Day Butter Cookies',
    price: 45.50,
    mrp: 50.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 4.50,
    inStock: true,
  },
  {
    id: 'oreo-original',
    name: 'Oreo Original Cream Biscuits',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '120g pack',
    brand: 'Oreo',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'lays-classic',
    name: 'Lays Classic Salted Chips',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '52g pack',
    brand: 'Lays',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'kurkure-masala',
    name: 'Kurkure Masala Munch',
    price: 10.00,
    mrp: 12.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '30g pack',
    brand: 'Kurkure',
    offers: ['Best Price'],
    margin: 2.00,
    inStock: true,
  },
  {
    id: 'haldirams-mixture',
    name: 'Haldirams Mixture',
    price: 15.00,
    mrp: 18.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '50g pack',
    brand: 'Haldirams',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: 'britannia-tiger',
    name: 'Britannia Tiger Glucose Biscuits',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sunfeast-dark-fantasy',
    name: 'Sunfeast Dark Fantasy Choco Fills',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '75g pack',
    brand: 'Sunfeast',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'cadbury-oreo',
    name: 'Cadbury Oreo Original',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '120g pack',
    brand: 'Cadbury',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'hide-seek',
    name: 'Hide & Seek Chocolate Chip Cookies',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'good-day-cashew',
    name: 'Good Day Cashew Cookies',
    price: 50.00,
    mrp: 55.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'bourbon-cream',
    name: 'Bourbon Cream Biscuits',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'nutri-choice',
    name: 'Nutri Choice Digestive Biscuits',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'marie-gold',
    name: 'Marie Gold Biscuits',
    price: 15.00,
    mrp: 18.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: '50-50-maska',
    name: '50-50 Maska Chaska',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'hide-seek-milkshake',
    name: 'Hide & Seek Milkshake',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'good-day-pista',
    name: 'Good Day Pista Cookies',
    price: 55.00,
    mrp: 60.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sunfeast-moments',
    name: 'Sunfeast Moments',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Sunfeast',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'parle-g-happy',
    name: 'Parle-G Happy Happy',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'britannia-nutri-choice',
    name: 'Britannia Nutri Choice 5 Grain',
    price: 50.00,
    mrp: 55.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sunfeast-bounce',
    name: 'Sunfeast Bounce',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Sunfeast',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'parle-krackjack-sweet',
    name: 'Parle Krackjack Sweet & Salty',
    price: 12.00,
    mrp: 15.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: 'britannia-good-day-chocolate',
    name: 'Good Day Chocolate Cookies',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'maggi-noodles',
    name: 'Maggi 2-Minute Masala Noodles',
    price: 14.00,
    mrp: 16.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/884600/pexels-photo-884600.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '70g pack',
    brand: 'Maggi',
    offers: ['2 Offers'],
    margin: 2.00,
    inStock: true,
  },
  {
    id: 'almonds-premium',
    name: 'Premium California Almonds',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '500g pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'cashews-roasted',
    name: 'Roasted Cashew Nuts',
    price: 380.00,
    mrp: 420.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '250g pack',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'cornflakes-kelloggs',
    name: 'Kelloggs Corn Flakes',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/5946071/pexels-photo-5946071.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '475g pack',
    brand: 'Kelloggs',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },

  // Home Care Products
  {
    id: 'surf-excel',
    name: 'Surf Excel Easy Wash Detergent Powder',
    price: 85.00,
    mrp: 100.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '1kg pack',
    brand: 'Surf Excel',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'vim-liquid',
    name: 'Vim Liquid Dish Wash',
    price: 125.00,
    mrp: 140.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Vim',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'harpic-toilet-cleaner',
    name: 'Harpic Powerplus Toilet Cleaner',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Harpic',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'dettol-antiseptic',
    name: 'Dettol Antiseptic Liquid',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '250ml bottle',
    brand: 'Dettol',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'lizol-floor-cleaner',
    name: 'Lizol Disinfectant Floor Cleaner',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Lizol',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'ariel-detergent',
    name: 'Ariel Matic Front Load Detergent',
    price: 320.00,
    mrp: 360.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '2kg pack',
    brand: 'Ariel',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'colin-glass-cleaner',
    name: 'Colin Glass & Surface Cleaner',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml spray',
    brand: 'Colin',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },

  // Beverages
  {
    id: 'bournvita',
    name: 'Cadbury Bournvita Health Drink',
    price: 280.00,
    mrp: 320.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '500g jar',
    brand: 'Cadbury',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'tata-gold',
    name: 'Tata Gold Tea',
    price: 165.00,
    mrp: 180.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Tata',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'nescafe-classic',
    name: 'Nescafe Classic Instant Coffee',
    price: 220.00,
    mrp: 250.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '200g jar',
    brand: 'Nescafe',
    offers: ['Best Price'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'red-label-tea',
    name: 'Red Label Natural Care Tea',
    price: 140.00,
    mrp: 155.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Red Label',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'horlicks-classic',
    name: 'Horlicks Health & Nutrition Drink',
    price: 350.00,
    mrp: 390.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '500g jar',
    brand: 'Horlicks',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'real-juice',
    name: 'Real Mixed Fruit Juice',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '1L pack',
    brand: 'Real',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'coca-cola',
    name: 'Coca Cola Soft Drink',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Coca Cola',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },

  // Personal Care
  {
    id: 'clinic-plus',
    name: 'Clinic Plus Shampoo',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '340ml bottle',
    brand: 'Clinic Plus',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'ponds-cream',
    name: 'Ponds Light Moisturizer',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100ml jar',
    brand: 'Ponds',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'colgate-toothpaste',
    name: 'Colgate Total Advanced Health',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '140g tube',
    brand: 'Colgate',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'head-shoulders',
    name: 'Head & Shoulders Anti-Dandruff Shampoo',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '340ml bottle',
    brand: 'Head & Shoulders',
    offers: ['Offer Applicable'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'dove-soap',
    name: 'Dove Beauty Bar Soap',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '125g bar',
    brand: 'Dove',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'nivea-cream',
    name: 'Nivea Soft Light Moisturizer',
    price: 140.00,
    mrp: 160.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200ml tube',
    brand: 'Nivea',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'listerine-mouthwash',
    name: 'Listerine Cool Mint Mouthwash',
    price: 165.00,
    mrp: 185.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '250ml bottle',
    brand: 'Listerine',
    offers: ['Offer Applicable'],
    margin: 20.00,
    inStock: true,
  },

  // Rice, Atta & Dals
  {
    id: 'india-gate-basmati',
    name: 'India Gate Basmati Rice',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '5kg pack',
    brand: 'India Gate',
    offers: ['Best Price'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'aashirvaad-atta',
    name: 'Aashirvaad Whole Wheat Atta',
    price: 280.00,
    mrp: 310.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '5kg pack',
    brand: 'Aashirvaad',
    offers: ['2 Offers'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'toor-dal',
    name: 'Premium Toor Dal',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'moong-dal',
    name: 'Yellow Moong Dal',
    price: 110.00,
    mrp: 125.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal Premium Quality',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'rajma-red',
    name: 'Red Rajma Kidney Beans',
    price: 140.00,
    mrp: 160.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },

  // Oil, Sugar & Masalas
  {
    id: 'fortune-sunflower-oil',
    name: 'Fortune Sunflower Oil',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Fortune',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'tata-salt',
    name: 'Tata Salt Iodized',
    price: 22.00,
    mrp: 25.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Tata',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: 'sugar-white',
    name: 'Premium White Sugar',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'mdh-garam-masala',
    name: 'MDH Garam Masala',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'MDH',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'everest-turmeric',
    name: 'Everest Turmeric Powder',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '200g pack',
    brand: 'Everest',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'ghee-amul',
    name: 'Amul Pure Ghee',
    price: 520.00,
    mrp: 580.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L tin',
    brand: 'Amul',
    offers: ['Best Price'],
    margin: 60.00,
    inStock: true,
  },

  // Dairy, Fresh & Frozen
  {
    id: 'amul-milk',
    name: 'Amul Taza Fresh Milk',
    price: 28.00,
    mrp: 30.00,
    discount: 7,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500ml pack',
    brand: 'Amul',
    offers: ['Best Price'],
    margin: 2.00,
    inStock: true,
  },
  {
    id: 'amul-butter',
    name: 'Amul Salted Butter',
    price: 55.00,
    mrp: 60.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '100g pack',
    brand: 'Amul',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'britannia-cheese',
    name: 'Britannia Cheese Slices',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '200g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'nestle-yogurt',
    name: 'Nestle A+ Greek Yogurt',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '400g cup',
    brand: 'Nestle',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'frozen-peas',
    name: 'Frozen Green Peas',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'paneer-fresh',
    name: 'Fresh Paneer Cottage Cheese',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '200g pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },

  // Luggage & Apparel
  {
    id: 'vip-trolley-bag',
    name: 'VIP Trolley Travel Bag',
    price: 2800.00,
    mrp: 3200.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '65cm hard case',
    brand: 'VIP',
    offers: ['Best Price'],
    margin: 400.00,
    inStock: true,
  },
  {
    id: 'american-tourister',
    name: 'American Tourister Backpack',
    price: 1800.00,
    mrp: 2000.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '30L capacity',
    brand: 'American Tourister',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'cotton-tshirt',
    name: 'Premium Cotton T-Shirt',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Size M, L, XL',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'formal-shirt',
    name: 'Formal Cotton Shirt',
    price: 850.00,
    mrp: 950.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Size M, L, XL',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
  },
  {
    id: 'sports-shoes',
    name: 'Sports Running Shoes',
    price: 1200.00,
    mrp: 1400.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Size 7-11',
    brand: 'Sports',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'leather-wallet',
    name: 'Genuine Leather Wallet',
    price: 650.00,
    mrp: 750.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Brown/Black',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
  },

  // Oil, Sugar & Masalas
  {
    id: 'fortune-rice-bran',
    name: 'Fortune Rice Bran Oil',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Fortune',
    offers: ['Offer Applicable'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'saffola-gold',
    name: 'Saffola Gold Refined Oil',
    price: 150.00,
    mrp: 170.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Saffola',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'dhara-mustard',
    name: 'Dhara Mustard Oil',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Dhara',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'patanjali-ghee',
    name: 'Patanjali Cow Ghee',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Patanjali',
    offers: ['Offer Applicable'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'amul-ghee',
    name: 'Amul Pure Ghee',
    price: 520.00,
    mrp: 580.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Amul',
    offers: ['2 Offers'],
    margin: 60.00,
    inStock: true,
  },
  {
    id: 'tata-salt',
    name: 'Tata Salt Iodized',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Tata',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sugar-refined',
    name: 'Refined Sugar',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'mdh-garam-masala',
    name: 'MDH Garam Masala',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'MDH',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'everest-chicken-masala',
    name: 'Everest Chicken Masala',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Everest',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'catch-chat-masala',
    name: 'Catch Chat Masala',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Catch',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'patanjali-turmeric',
    name: 'Patanjali Turmeric Powder',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '200g pack',
    brand: 'Patanjali',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'red-chilli-powder',
    name: 'Red Chilli Powder',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'coriander-powder',
    name: 'Coriander Powder',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'cumin-powder',
    name: 'Cumin Powder',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'black-pepper',
    name: 'Black Pepper Powder',
    price: 60.00,
    mrp: 70.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'cardamom-powder',
    name: 'Cardamom Powder',
    price: 80.00,
    mrp: 90.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'cinnamon-powder',
    name: 'Cinnamon Powder',
    price: 70.00,
    mrp: 80.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'nutmeg-powder',
    name: 'Nutmeg Powder',
    price: 90.00,
    mrp: 100.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'clove-powder',
    name: 'Clove Powder',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'bay-leaves',
    name: 'Bay Leaves',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'fenugreek-powder',
    name: 'Fenugreek Powder',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },

  // Kitchen & Home Appliances (10 items)
  {
    id: 'pressure-cooker-hawkins',
    name: 'Hawkins Pressure Cooker',
    price: 1200.00,
    mrp: 1500.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '3L capacity',
    brand: 'Hawkins',
    offers: ['Best Price'],
    margin: 300.00,
    inStock: true,
    weight: '3L',
    packType: 'Box',
  },
  {
    id: 'mixer-grinder-preethi',
    name: 'Preethi Mixer Grinder',
    price: 2800.00,
    mrp: 3500.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '750W motor',
    brand: 'Preethi',
    offers: ['2 Offers'],
    margin: 700.00,
    inStock: true,
    weight: '750W',
    packType: 'Box',
  },
  {
    id: 'gas-stove-butterfly',
    name: 'Butterfly Gas Stove',
    price: 1800.00,
    mrp: 2200.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '2 burner',
    brand: 'Butterfly',
    offers: ['Offer Applicable'],
    margin: 400.00,
    inStock: true,
    weight: '2 Burner',
    packType: 'Box',
  },
  {
    id: 'rice-cooker-panasonic',
    name: 'Panasonic Rice Cooker',
    price: 2200.00,
    mrp: 2800.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '1.8L capacity',
    brand: 'Panasonic',
    offers: ['Best Price'],
    margin: 600.00,
    inStock: true,
    weight: '1.8L',
    packType: 'Box',
  },
  {
    id: 'induction-cooktop-prestige',
    name: 'Prestige Induction Cooktop',
    price: 1500.00,
    mrp: 1900.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '1600W',
    brand: 'Prestige',
    offers: ['2 Offers'],
    margin: 400.00,
    inStock: true,
    weight: '1600W',
    packType: 'Box',
  },
  {
    id: 'water-filter-kent',
    name: 'Kent Water Purifier',
    price: 8500.00,
    mrp: 12000.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: 'RO+UV+UF',
    brand: 'Kent',
    offers: ['Offer Applicable'],
    margin: 3500.00,
    inStock: true,
    weight: 'RO+UV+UF',
    packType: 'Box',
  },
  {
    id: 'microwave-lg',
    name: 'LG Microwave Oven',
    price: 6500.00,
    mrp: 8500.00,
    discount: 24,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '20L capacity',
    brand: 'LG',
    offers: ['Best Price'],
    margin: 2000.00,
    inStock: true,
    weight: '20L',
    packType: 'Box',
  },
  {
    id: 'toaster-philips',
    name: 'Philips Bread Toaster',
    price: 1200.00,
    mrp: 1600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '2 slice',
    brand: 'Philips',
    offers: ['2 Offers'],
    margin: 400.00,
    inStock: true,
    weight: '2 Slice',
    packType: 'Box',
  },
  {
    id: 'kettle-bajaj',
    name: 'Bajaj Electric Kettle',
    price: 800.00,
    mrp: 1200.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '1.5L capacity',
    brand: 'Bajaj',
    offers: ['Offer Applicable'],
    margin: 400.00,
    inStock: true,
    weight: '1.5L',
    packType: 'Box',
  },
  {
    id: 'blender-bajaj',
    name: 'Bajaj Hand Blender',
    price: 900.00,
    mrp: 1300.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'kitchenappliances',
    description: '200W motor',
    brand: 'Bajaj',
    offers: ['Best Price'],
    margin: 400.00,
    inStock: true,
    weight: '200W',
    packType: 'Box',
  },

  // Beauty & Cosmetics (10 items)
  {
    id: 'lakme-foundation',
    name: 'Lakme Absolute Foundation',
    price: 450.00,
    mrp: 550.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '25ml bottle',
    brand: 'Lakme',
    offers: ['2 Offers'],
    margin: 100.00,
    inStock: true,
    weight: '25ml',
    packType: 'Bottle',
  },
  {
    id: 'maybelline-lipstick',
    name: 'Maybelline Lipstick',
    price: 350.00,
    mrp: 450.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '3.9g tube',
    brand: 'Maybelline',
    offers: ['Offer Applicable'],
    margin: 100.00,
    inStock: true,
    weight: '3.9g',
    packType: 'Tube',
  },
  {
    id: 'loreal-shampoo',
    name: 'L\'Oreal Hair Shampoo',
    price: 280.00,
    mrp: 350.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '340ml bottle',
    brand: 'L\'Oreal',
    offers: ['Best Price'],
    margin: 70.00,
    inStock: true,
    weight: '340ml',
    packType: 'Bottle',
  },
  {
    id: 'olay-moisturizer',
    name: 'Olay Moisturizing Cream',
    price: 320.00,
    mrp: 400.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '50g jar',
    brand: 'Olay',
    offers: ['2 Offers'],
    margin: 80.00,
    inStock: true,
    weight: '50g',
    packType: 'Jar',
  },
  {
    id: 'garnier-facewash',
    name: 'Garnier Face Wash',
    price: 120.00,
    mrp: 150.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '100g tube',
    brand: 'Garnier',
    offers: ['Offer Applicable'],
    margin: 30.00,
    inStock: true,
    weight: '100g',
    packType: 'Tube',
  },
  {
    id: 'nivea-body-lotion',
    name: 'Nivea Body Lotion',
    price: 180.00,
    mrp: 220.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '200ml bottle',
    brand: 'Nivea',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
    weight: '200ml',
    packType: 'Bottle',
  },
  {
    id: 'himalaya-face-cream',
    name: 'Himalaya Face Cream',
    price: 85.00,
    mrp: 110.00,
    discount: 23,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '50g tube',
    brand: 'Himalaya',
    offers: ['2 Offers'],
    margin: 25.00,
    inStock: true,
    weight: '50g',
    packType: 'Tube',
  },
  {
    id: 'biotique-hair-oil',
    name: 'Biotique Hair Oil',
    price: 140.00,
    mrp: 180.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '120ml bottle',
    brand: 'Biotique',
    offers: ['Offer Applicable'],
    margin: 40.00,
    inStock: true,
    weight: '120ml',
    packType: 'Bottle',
  },
  {
    id: 'patanjali-aloe-gel',
    name: 'Patanjali Aloe Vera Gel',
    price: 65.00,
    mrp: 85.00,
    discount: 24,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '150ml tube',
    brand: 'Patanjali',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
    weight: '150ml',
    packType: 'Tube',
  },
  {
    id: 'dabur-gulabari',
    name: 'Dabur Gulabari Rose Water',
    price: 55.00,
    mrp: 75.00,
    discount: 27,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beauty',
    description: '120ml bottle',
    brand: 'Dabur',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
    weight: '120ml',
    packType: 'Bottle',
  },

  // Baby Care & Toys (10 items)
  {
    id: 'pampers-diapers',
    name: 'Pampers Baby Diapers',
    price: 450.00,
    mrp: 550.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: 'Medium size, 42 count',
    brand: 'Pampers',
    offers: ['2 Offers'],
    margin: 100.00,
    inStock: true,
    weight: '42 Count',
    packType: 'Pack',
  },
  {
    id: 'johnson-baby-oil',
    name: 'Johnson\'s Baby Oil',
    price: 120.00,
    mrp: 150.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '200ml bottle',
    brand: 'Johnson\'s',
    offers: ['Offer Applicable'],
    margin: 30.00,
    inStock: true,
    weight: '200ml',
    packType: 'Bottle',
  },
  {
    id: 'cerelac-baby-food',
    name: 'Nestle Cerelac Baby Food',
    price: 180.00,
    mrp: 220.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '300g pack',
    brand: 'Nestle',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
    weight: '300g',
    packType: 'Pack',
  },
  {
    id: 'himalaya-baby-soap',
    name: 'Himalaya Baby Soap',
    price: 45.00,
    mrp: 60.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '75g bar',
    brand: 'Himalaya',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
    weight: '75g',
    packType: 'Bar',
  },
  {
    id: 'mee-mee-feeding-bottle',
    name: 'Mee Mee Feeding Bottle',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '150ml bottle',
    brand: 'Mee Mee',
    offers: ['Offer Applicable'],
    margin: 70.00,
    inStock: true,
    weight: '150ml',
    packType: 'Bottle',
  },
  {
    id: 'chicco-baby-shampoo',
    name: 'Chicco Baby Shampoo',
    price: 220.00,
    mrp: 280.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '200ml bottle',
    brand: 'Chicco',
    offers: ['Best Price'],
    margin: 60.00,
    inStock: true,
    weight: '200ml',
    packType: 'Bottle',
  },
  {
    id: 'fisher-price-toy',
    name: 'Fisher Price Baby Toy',
    price: 850.00,
    mrp: 1200.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: 'Musical toy',
    brand: 'Fisher Price',
    offers: ['2 Offers'],
    margin: 350.00,
    inStock: true,
    weight: 'Musical',
    packType: 'Box',
  },
  {
    id: 'huggies-wipes',
    name: 'Huggies Baby Wipes',
    price: 120.00,
    mrp: 150.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '80 wipes',
    brand: 'Huggies',
    offers: ['Offer Applicable'],
    margin: 30.00,
    inStock: true,
    weight: '80 Wipes',
    packType: 'Pack',
  },
  {
    id: 'pigeon-baby-powder',
    name: 'Pigeon Baby Powder',
    price: 85.00,
    mrp: 110.00,
    discount: 23,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '100g bottle',
    brand: 'Pigeon',
    offers: ['Best Price'],
    margin: 25.00,
    inStock: true,
    weight: '100g',
    packType: 'Bottle',
  },
  {
    id: 'mothercare-baby-lotion',
    name: 'Mothercare Baby Lotion',
    price: 160.00,
    mrp: 200.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1648377/pexels-photo-1648377.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'babycare',
    description: '200ml bottle',
    brand: 'Mothercare',
    offers: ['2 Offers'],
    margin: 40.00,
    inStock: true,
    weight: '200ml',
    packType: 'Bottle',
  },

  // Pet Care (10 items)
  {
    id: 'pedigree-dog-food',
    name: 'Pedigree Adult Dog Food',
    price: 320.00,
    mrp: 400.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '1.2kg pack',
    brand: 'Pedigree',
    offers: ['2 Offers'],
    margin: 80.00,
    inStock: true,
    weight: '1.2kg',
    packType: 'Pack',
  },
  {
    id: 'whiskas-cat-food',
    name: 'Whiskas Cat Food',
    price: 180.00,
    mrp: 220.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '480g pack',
    brand: 'Whiskas',
    offers: ['Offer Applicable'],
    margin: 40.00,
    inStock: true,
    weight: '480g',
    packType: 'Pack',
  },
  {
    id: 'royal-canin-dog-food',
    name: 'Royal Canin Dog Food',
    price: 850.00,
    mrp: 1000.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '1.5kg pack',
    brand: 'Royal Canin',
    offers: ['Best Price'],
    margin: 150.00,
    inStock: true,
    weight: '1.5kg',
    packType: 'Pack',
  },
  {
    id: 'drools-dog-treats',
    name: 'Drools Dog Treats',
    price: 120.00,
    mrp: 150.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '150g pack',
    brand: 'Drools',
    offers: ['2 Offers'],
    margin: 30.00,
    inStock: true,
    weight: '150g',
    packType: 'Pack',
  },
  {
    id: 'pet-shampoo-himalaya',
    name: 'Himalaya Pet Shampoo',
    price: 180.00,
    mrp: 220.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '200ml bottle',
    brand: 'Himalaya',
    offers: ['Offer Applicable'],
    margin: 40.00,
    inStock: true,
    weight: '200ml',
    packType: 'Bottle',
  },
  {
    id: 'pet-collar-leather',
    name: 'Leather Pet Collar',
    price: 250.00,
    mrp: 350.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: 'Medium size',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
    weight: 'Medium',
    packType: 'Piece',
  },
  {
    id: 'pet-toy-ball',
    name: 'Pet Rubber Ball Toy',
    price: 80.00,
    mrp: 120.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: 'Medium size',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 40.00,
    inStock: true,
    weight: 'Medium',
    packType: 'Piece',
  },
  {
    id: 'pet-food-bowl',
    name: 'Stainless Steel Pet Bowl',
    price: 150.00,
    mrp: 200.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '500ml capacity',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 50.00,
    inStock: true,
    weight: '500ml',
    packType: 'Piece',
  },
  {
    id: 'pet-leash',
    name: 'Nylon Pet Leash',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: '1.2m length',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 70.00,
    inStock: true,
    weight: '1.2m',
    packType: 'Piece',
  },
  {
    id: 'pet-bed',
    name: 'Soft Pet Bed',
    price: 450.00,
    mrp: 600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'petcare',
    description: 'Medium size',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 150.00,
    inStock: true,
    weight: 'Medium',
    packType: 'Piece',
  },

  // Automotive (10 items)
  {
    id: 'castrol-engine-oil',
    name: 'Castrol Engine Oil',
    price: 450.00,
    mrp: 550.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: '1L bottle',
    brand: 'Castrol',
    offers: ['2 Offers'],
    margin: 100.00,
    inStock: true,
    weight: '1L',
    packType: 'Bottle',
  },
  {
    id: 'mobil-engine-oil',
    name: 'Mobil 1 Engine Oil',
    price: 520.00,
    mrp: 650.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: '1L bottle',
    brand: 'Mobil',
    offers: ['Offer Applicable'],
    margin: 130.00,
    inStock: true,
    weight: '1L',
    packType: 'Bottle',
  },
  {
    id: 'car-air-freshener',
    name: 'Car Air Freshener',
    price: 85.00,
    mrp: 120.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: 'Vanilla scent',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 35.00,
    inStock: true,
    weight: 'Vanilla',
    packType: 'Piece',
  },
  {
    id: 'car-wash-shampoo',
    name: 'Car Wash Shampoo',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: '500ml bottle',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 70.00,
    inStock: true,
    weight: '500ml',
    packType: 'Bottle',
  },
  {
    id: 'tire-pressure-gauge',
    name: 'Digital Tire Pressure Gauge',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: 'Digital display',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 130.00,
    inStock: true,
    weight: 'Digital',
    packType: 'Piece',
  },
  {
    id: 'car-phone-holder',
    name: 'Car Phone Holder',
    price: 150.00,
    mrp: 250.00,
    discount: 40,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: 'Dashboard mount',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
    weight: 'Dashboard',
    packType: 'Piece',
  },
  {
    id: 'car-charger',
    name: 'Car USB Charger',
    price: 180.00,
    mrp: 280.00,
    discount: 36,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: 'Dual USB ports',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 100.00,
    inStock: true,
    weight: 'Dual USB',
    packType: 'Piece',
  },
  {
    id: 'car-seat-cover',
    name: 'Car Seat Cover Set',
    price: 850.00,
    mrp: 1200.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: 'Full set',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 350.00,
    inStock: true,
    weight: 'Full Set',
    packType: 'Set',
  },
  {
    id: 'car-floor-mats',
    name: 'Car Floor Mats',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: 'Set of 4',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 200.00,
    inStock: true,
    weight: 'Set of 4',
    packType: 'Set',
  },
  {
    id: 'car-dashboard-cleaner',
    name: 'Dashboard Cleaner Spray',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'automotive',
    description: '250ml spray',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 60.00,
    inStock: true,
    weight: '250ml',
    packType: 'Bottle',
  },

  // Sports & Fitness (10 items)
  {
    id: 'yoga-mat',
    name: 'Premium Yoga Mat',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: '6mm thickness',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
    weight: '6mm',
    packType: 'Piece',
  },
  {
    id: 'dumbbells-set',
    name: 'Adjustable Dumbbells Set',
    price: 1200.00,
    mrp: 1600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: '5kg each',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 400.00,
    inStock: true,
    weight: '5kg Each',
    packType: 'Set',
  },
  {
    id: 'resistance-bands',
    name: 'Resistance Bands Set',
    price: 280.00,
    mrp: 400.00,
    discount: 30,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: 'Set of 5',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 120.00,
    inStock: true,
    weight: 'Set of 5',
    packType: 'Set',
  },
  {
    id: 'protein-powder',
    name: 'Whey Protein Powder',
    price: 1800.00,
    mrp: 2200.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: '1kg container',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 400.00,
    inStock: true,
    weight: '1kg',
    packType: 'Container',
  },
  {
    id: 'sports-shoes',
    name: 'Running Sports Shoes',
    price: 1200.00,
    mrp: 1800.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: 'Size 8-11',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 600.00,
    inStock: true,
    weight: 'Size 8-11',
    packType: 'Pair',
  },
  {
    id: 'cricket-bat',
    name: 'Cricket Bat',
    price: 850.00,
    mrp: 1200.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: 'English willow',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 350.00,
    inStock: true,
    weight: 'English Willow',
    packType: 'Piece',
  },
  {
    id: 'badminton-racket',
    name: 'Badminton Racket',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: 'Carbon fiber',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
    weight: 'Carbon Fiber',
    packType: 'Piece',
  },
  {
    id: 'football',
    name: 'Football',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: 'Size 5',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 130.00,
    inStock: true,
    weight: 'Size 5',
    packType: 'Piece',
  },
  {
    id: 'gym-gloves',
    name: 'Gym Workout Gloves',
    price: 180.00,
    mrp: 280.00,
    discount: 36,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: 'Medium size',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
    weight: 'Medium',
    packType: 'Pair',
  },
  {
    id: 'water-bottle-sports',
    name: 'Sports Water Bottle',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/3822906/pexels-photo-3822906.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'sports',
    description: '750ml capacity',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 60.00,
    inStock: true,
    weight: '750ml',
    packType: 'Piece',
  },

  // Books & Stationery (10 items)
  {
    id: 'notebook-classmate',
    name: 'Classmate Notebook',
    price: 45.00,
    mrp: 60.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: '200 pages',
    brand: 'Classmate',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
    weight: '200 Pages',
    packType: 'Piece',
  },
  {
    id: 'pen-reynolds',
    name: 'Reynolds Ball Pen',
    price: 12.00,
    mrp: 18.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: 'Blue ink',
    brand: 'Reynolds',
    offers: ['Offer Applicable'],
    margin: 6.00,
    inStock: true,
    weight: 'Blue Ink',
    packType: 'Piece',
  },
  {
    id: 'pencil-apsara',
    name: 'Apsara Pencil Set',
    price: 25.00,
    mrp: 35.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: 'Pack of 10',
    brand: 'Apsara',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
    weight: 'Pack of 10',
    packType: 'Pack',
  },
  {
    id: 'eraser-apsara',
    name: 'Apsara Eraser',
    price: 8.00,
    mrp: 12.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: 'White eraser',
    brand: 'Apsara',
    offers: ['2 Offers'],
    margin: 4.00,
    inStock: true,
    weight: 'White',
    packType: 'Piece',
  },
  {
    id: 'ruler-plastic',
    name: 'Plastic Ruler',
    price: 15.00,
    mrp: 25.00,
    discount: 40,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: '30cm length',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
    weight: '30cm',
    packType: 'Piece',
  },
  {
    id: 'geometry-box',
    name: 'Geometry Box Set',
    price: 85.00,
    mrp: 120.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: 'Complete set',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 35.00,
    inStock: true,
    weight: 'Complete Set',
    packType: 'Set',
  },
  {
    id: 'color-pencils',
    name: 'Color Pencils Set',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: '24 colors',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 60.00,
    inStock: true,
    weight: '24 Colors',
    packType: 'Set',
  },
  {
    id: 'sketch-book',
    name: 'Sketch Book',
    price: 65.00,
    mrp: 90.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: 'A4 size',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 25.00,
    inStock: true,
    weight: 'A4 Size',
    packType: 'Piece',
  },
  {
    id: 'marker-pens',
    name: 'Marker Pens Set',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: '12 colors',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 70.00,
    inStock: true,
    weight: '12 Colors',
    packType: 'Set',
  },
  {
    id: 'calculator',
    name: 'Scientific Calculator',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/159751/book-address-book-learning-learn-159751.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'books',
    description: 'Scientific functions',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 130.00,
    inStock: true,
    weight: 'Scientific',
    packType: 'Piece',
  },

  // Garden & Outdoor (10 items)
  {
    id: 'plant-pot-ceramic',
    name: 'Ceramic Plant Pot',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: 'Medium size',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 70.00,
    inStock: true,
    weight: 'Medium',
    packType: 'Piece',
  },
  {
    id: 'garden-tools-set',
    name: 'Garden Tools Set',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: '5 piece set',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 200.00,
    inStock: true,
    weight: '5 Piece Set',
    packType: 'Set',
  },
  {
    id: 'watering-can',
    name: 'Plastic Watering Can',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: '2L capacity',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 60.00,
    inStock: true,
    weight: '2L',
    packType: 'Piece',
  },
  {
    id: 'fertilizer-organic',
    name: 'Organic Fertilizer',
    price: 85.00,
    mrp: 120.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 35.00,
    inStock: true,
    weight: '1kg',
    packType: 'Pack',
  },
  {
    id: 'garden-hose',
    name: 'Garden Water Hose',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: '10m length',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 130.00,
    inStock: true,
    weight: '10m',
    packType: 'Piece',
  },
  {
    id: 'plant-seeds',
    name: 'Vegetable Seeds Pack',
    price: 45.00,
    mrp: 65.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: 'Mixed variety',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
    weight: 'Mixed',
    packType: 'Pack',
  },
  {
    id: 'garden-gloves',
    name: 'Garden Work Gloves',
    price: 85.00,
    mrp: 120.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: 'Medium size',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 35.00,
    inStock: true,
    weight: 'Medium',
    packType: 'Pair',
  },
  {
    id: 'plant-stand',
    name: 'Metal Plant Stand',
    price: 280.00,
    mrp: 400.00,
    discount: 30,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: '3 tier',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 120.00,
    inStock: true,
    weight: '3 Tier',
    packType: 'Piece',
  },
  {
    id: 'garden-sprayer',
    name: 'Garden Spray Bottle',
    price: 65.00,
    mrp: 95.00,
    discount: 32,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: '500ml capacity',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 30.00,
    inStock: true,
    weight: '500ml',
    packType: 'Piece',
  },
  {
    id: 'outdoor-chair',
    name: 'Plastic Outdoor Chair',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'garden',
    description: 'Weather resistant',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
    weight: 'Weather Resistant',
    packType: 'Piece',
  },

  // Furniture & Home (10 items)
  {
    id: 'plastic-chair',
    name: 'Plastic Dining Chair',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: 'Stackable design',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 130.00,
    inStock: true,
    weight: 'Stackable',
    packType: 'Piece',
  },
  {
    id: 'study-table',
    name: 'Wooden Study Table',
    price: 1800.00,
    mrp: 2500.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: 'With drawer',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 700.00,
    inStock: true,
    weight: 'With Drawer',
    packType: 'Piece',
  },
  {
    id: 'bookshelf',
    name: 'Wooden Bookshelf',
    price: 2200.00,
    mrp: 3000.00,
    discount: 27,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: '5 shelves',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 800.00,
    inStock: true,
    weight: '5 Shelves',
    packType: 'Piece',
  },
  {
    id: 'office-chair',
    name: 'Office Revolving Chair',
    price: 1500.00,
    mrp: 2200.00,
    discount: 32,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: 'Adjustable height',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 700.00,
    inStock: true,
    weight: 'Adjustable',
    packType: 'Piece',
  },
  {
    id: 'storage-box',
    name: 'Plastic Storage Box',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: '50L capacity',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 70.00,
    inStock: true,
    weight: '50L',
    packType: 'Piece',
  },
  {
    id: 'wall-clock',
    name: 'Wall Clock',
    price: 280.00,
    mrp: 400.00,
    discount: 30,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: 'Analog display',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 120.00,
    inStock: true,
    weight: 'Analog',
    packType: 'Piece',
  },
  {
    id: 'table-lamp',
    name: 'LED Table Lamp',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: 'Adjustable brightness',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
    weight: 'Adjustable',
    packType: 'Piece',
  },
  {
    id: 'curtains',
    name: 'Window Curtains',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: '7ft length',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 130.00,
    inStock: true,
    weight: '7ft',
    packType: 'Pair',
  },
  {
    id: 'mirror',
    name: 'Wall Mirror',
    price: 380.00,
    mrp: 550.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: '18 inch diameter',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 170.00,
    inStock: true,
    weight: '18 Inch',
    packType: 'Piece',
  },
  {
    id: 'shoe-rack',
    name: 'Wooden Shoe Rack',
    price: 650.00,
    mrp: 900.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'furniture',
    description: '3 tier',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 250.00,
    inStock: true,
    weight: '3 Tier',
    packType: 'Piece',
  },

  // Restaurant Supplies & Houseware (10 items)
  {
    id: 'steel-plates-set',
    name: 'Stainless Steel Plates Set',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Set of 6',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
    weight: 'Set of 6',
    packType: 'Set',
  },
  {
    id: 'cooking-pot-steel',
    name: 'Stainless Steel Cooking Pot',
    price: 850.00,
    mrp: 1200.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: '5L capacity',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 350.00,
    inStock: true,
    weight: '5L',
    packType: 'Piece',
  },
  {
    id: 'kitchen-knife-set',
    name: 'Kitchen Knife Set',
    price: 650.00,
    mrp: 900.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Set of 5',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 250.00,
    inStock: true,
    weight: 'Set of 5',
    packType: 'Set',
  },
  {
    id: 'cutting-board',
    name: 'Wooden Cutting Board',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Large size',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 70.00,
    inStock: true,
    weight: 'Large',
    packType: 'Piece',
  },
  {
    id: 'storage-containers',
    name: 'Food Storage Containers',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Set of 4',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 130.00,
    inStock: true,
    weight: 'Set of 4',
    packType: 'Set',
  },
  {
    id: 'serving-spoons',
    name: 'Serving Spoons Set',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Set of 6',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 60.00,
    inStock: true,
    weight: 'Set of 6',
    packType: 'Set',
  },
  {
    id: 'kitchen-towels',
    name: 'Kitchen Towels',
    price: 85.00,
    mrp: 120.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Pack of 3',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 35.00,
    inStock: true,
    weight: 'Pack of 3',
    packType: 'Pack',
  },
  {
    id: 'mixing-bowls',
    name: 'Stainless Steel Mixing Bowls',
    price: 280.00,
    mrp: 400.00,
    discount: 30,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Set of 3',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 120.00,
    inStock: true,
    weight: 'Set of 3',
    packType: 'Set',
  },
  {
    id: 'kitchen-scale',
    name: 'Digital Kitchen Scale',
    price: 650.00,
    mrp: 900.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: '5kg capacity',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 250.00,
    inStock: true,
    weight: '5kg',
    packType: 'Piece',
  },
  {
    id: 'apron',
    name: 'Kitchen Apron',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'restaurantsupplies',
    description: 'Waterproof',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 60.00,
    inStock: true,
    weight: 'Waterproof',
    packType: 'Piece',
  },

  // IT Stationary & Office Furniture (10 items)
  {
    id: 'computer-mouse',
    name: 'Wireless Computer Mouse',
    price: 320.00,
    mrp: 450.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: 'Optical sensor',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 130.00,
    inStock: true,
    weight: 'Optical',
    packType: 'Piece',
  },
  {
    id: 'keyboard-usb',
    name: 'USB Keyboard',
    price: 450.00,
    mrp: 650.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: 'Standard layout',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 200.00,
    inStock: true,
    weight: 'Standard',
    packType: 'Piece',
  },
  {
    id: 'usb-cable',
    name: 'USB Data Cable',
    price: 85.00,
    mrp: 120.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: '1.5m length',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 35.00,
    inStock: true,
    weight: '1.5m',
    packType: 'Piece',
  },
  {
    id: 'power-strip',
    name: 'Power Strip Extension',
    price: 280.00,
    mrp: 400.00,
    discount: 30,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: '6 sockets',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 120.00,
    inStock: true,
    weight: '6 Sockets',
    packType: 'Piece',
  },
  {
    id: 'printer-paper',
    name: 'A4 Printer Paper',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: '500 sheets',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 70.00,
    inStock: true,
    weight: '500 Sheets',
    packType: 'Pack',
  },
  {
    id: 'file-folders',
    name: 'File Folders Set',
    price: 120.00,
    mrp: 180.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: 'Pack of 10',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 60.00,
    inStock: true,
    weight: 'Pack of 10',
    packType: 'Pack',
  },
  {
    id: 'stapler',
    name: 'Heavy Duty Stapler',
    price: 180.00,
    mrp: 250.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: '50 sheet capacity',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 70.00,
    inStock: true,
    weight: '50 Sheet',
    packType: 'Piece',
  },
  {
    id: 'desk-organizer',
    name: 'Desk Organizer Tray',
    price: 220.00,
    mrp: 320.00,
    discount: 31,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: 'Multi compartment',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 100.00,
    inStock: true,
    weight: 'Multi Compartment',
    packType: 'Piece',
  },
  {
    id: 'whiteboard',
    name: 'Magnetic Whiteboard',
    price: 650.00,
    mrp: 900.00,
    discount: 28,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: '2x3 feet',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 250.00,
    inStock: true,
    weight: '2x3 Feet',
    packType: 'Piece',
  },
  {
    id: 'paper-shredder',
    name: 'Paper Shredder',
    price: 1200.00,
    mrp: 1600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/2115217/pexels-photo-2115217.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'itstationary',
    description: 'Cross cut',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 400.00,
    inStock: true,
    weight: 'Cross Cut',
    packType: 'Piece',
  },
  ...additionalProducts,
  ...moreProducts,
  ...remainingProducts,
  ...electronicsProducts,
];

export const brands = [
  { name: 'Surf Excel', logo: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Colgate', logo: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Dettol', logo: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Harpic', logo: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Parle', logo: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Amul', logo: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Tata', logo: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Britannia', logo: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=100' },
];