import { Product, Category } from '@/types';
import { additionalProducts } from './additional_products';
import { moreProducts } from './more_products';
import { remainingProducts } from './remaining_products';
import { electronicsProducts } from './electronics_products';

export const categories: Category[] = [
  {
    id: 'homecare',
    name: 'Home care',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&h=300&fit=crop',
    subcategories: ['Cleaning Supplies', 'Laundry', 'Kitchen Care', 'Bathroom Care']
  },
  {
    id: 'beverages',
    name: 'Beverages',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=300&h=300&fit=crop',
    subcategories: ['Tea', 'Coffee', 'Juices', 'Soft Drinks', 'Energy Drinks']
  },
  {
    id: 'personalcare',
    name: 'Personal care',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop',
    subcategories: ['Skincare', 'Haircare', 'Oral Care', 'Bath & Body']
  },
  {
    id: 'ricedals',
    name: 'Rice, Atta & Dals',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop',
    subcategories: ['Rice', 'Wheat & Flour', 'Pulses', 'Grains']
  },
  {
    id: 'packagedfoods',
    name: 'Packaged Foods & Dry Fruits',
    image: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=300&h=300&fit=crop',
    subcategories: ['Biscuits', 'Snacks', 'Dry Fruits', 'Cereals', 'Instant Foods', 'Nuts & Seeds']
  },
  {
    id: 'oilsugar',
    name: 'Oil, Sugar & Masalas',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=300&fit=crop',
    subcategories: ['Cooking Oil', 'Sugar', 'Spices', 'Salt', 'Ghee', 'Masalas', 'Condiments']
  },
  {
    id: 'dailyfresh',
    name: 'Daily Fresh & Frozen',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&h=300&fit=crop',
    subcategories: ['Fresh Vegetables', 'Fresh Fruits', 'Frozen Foods', 'Dairy Products', 'Meat & Fish']
  },
  {
    id: 'kitchenappliances',
    name: 'Kitchen & Home Appliances',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=300&fit=crop',
    subcategories: ['Kitchen Appliances', 'Home Appliances', 'Cookware', 'Small Appliances', 'Kitchen Tools']
  },
  {
    id: 'beauty',
    name: 'Beauty & Cosmetics',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=300&h=300&fit=crop',
    subcategories: ['Makeup', 'Skincare', 'Fragrances', 'Hair Products', 'Nail Care']
  },
  {
    id: 'babycare',
    name: 'Baby Care & Toys',
    image: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?w=300&h=300&fit=crop',
    subcategories: ['Diapers', 'Baby Food', 'Toys', 'Clothing', 'Care Products']
  },
  {
    id: 'petcare',
    name: 'Pet Care',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=300&h=300&fit=crop',
    subcategories: ['Pet Food', 'Toys', 'Grooming', 'Accessories', 'Health Care']
  },
  {
    id: 'automotive',
    name: 'Automotive',
    image: 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=300&h=300&fit=crop',
    subcategories: ['Car Care', 'Accessories', 'Tools', 'Oils', 'Spare Parts']
  },
  {
    id: 'sports',
    name: 'Sports & Fitness',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop',
    subcategories: ['Fitness Equipment', 'Sports Gear', 'Activewear', 'Supplements', 'Yoga']
  },
  {
    id: 'books',
    name: 'Books & Stationery',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop',
    subcategories: ['Books', 'Notebooks', 'Pens', 'Art Supplies', 'Office Supplies']
  },
  {
    id: 'garden',
    name: 'Garden & Outdoor',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300&h=300&fit=crop',
    subcategories: ['Plants', 'Garden Tools', 'Outdoor Furniture', 'BBQ', 'Decor']
  },
  {
    id: 'furniture',
    name: 'Furniture & Home',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=300&fit=crop',
    subcategories: ['Living Room', 'Bedroom', 'Kitchen', 'Office', 'Outdoor']
  },
  {
    id: 'restaurantsupplies',
    name: 'Restaurant Supplies & Houseware',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&h=300&fit=crop',
    subcategories: ['Kitchen Equipment', 'Serving Dishes', 'Cleaning Supplies', 'Storage Containers', 'Utensils']
  },
  {
    id: 'itstationary',
    name: 'IT Stationary & Office Furniture',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=300&fit=crop',
    subcategories: ['Computers', 'Office Supplies', 'Furniture', 'Electronics', 'Stationery', 'Printers']
  }
];

export const products: Product[] = [
  // Packaged Foods & Dry Fruits (Biscuits, Snacks, etc.)
  {
    id: 'parle-krackjack',
    name: 'Parle Krackjack Sweet & Salty Biscuits',
    price: 9.09,
    mrp: 10.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '56.7 g + 6.3 g',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 0.91,
    inStock: true,
  },
  {
    id: 'parle-monaco',
    name: 'Parle Monaco Biscuit 400 g',
    price: 72.73,
    mrp: 80.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '400g pack',
    brand: 'Parle',
    offers: ['3 Offers'],
    margin: 7.27,
    inStock: true,
  },
  {
    id: 'britannia-goodday',
    name: 'Britannia Good Day Butter Cookies',
    price: 45.50,
    mrp: 50.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 4.50,
    inStock: true,
  },
  {
    id: 'oreo-original',
    name: 'Oreo Original Cream Biscuits',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '120g pack',
    brand: 'Oreo',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'lays-classic',
    name: 'Lays Classic Salted Chips',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '52g pack',
    brand: 'Lays',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'kurkure-masala',
    name: 'Kurkure Masala Munch',
    price: 10.00,
    mrp: 12.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '30g pack',
    brand: 'Kurkure',
    offers: ['Best Price'],
    margin: 2.00,
    inStock: true,
  },
  {
    id: 'haldirams-mixture',
    name: 'Haldirams Mixture',
    price: 15.00,
    mrp: 18.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '50g pack',
    brand: 'Haldirams',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: 'britannia-tiger',
    name: 'Britannia Tiger Glucose Biscuits',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sunfeast-dark-fantasy',
    name: 'Sunfeast Dark Fantasy Choco Fills',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '75g pack',
    brand: 'Sunfeast',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'cadbury-oreo',
    name: 'Cadbury Oreo Original',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '120g pack',
    brand: 'Cadbury',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'hide-seek',
    name: 'Hide & Seek Chocolate Chip Cookies',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'good-day-cashew',
    name: 'Good Day Cashew Cookies',
    price: 50.00,
    mrp: 55.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'bourbon-cream',
    name: 'Bourbon Cream Biscuits',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'nutri-choice',
    name: 'Nutri Choice Digestive Biscuits',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'marie-gold',
    name: 'Marie Gold Biscuits',
    price: 15.00,
    mrp: 18.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: '50-50-maska',
    name: '50-50 Maska Chaska',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'hide-seek-milkshake',
    name: 'Hide & Seek Milkshake',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'good-day-pista',
    name: 'Good Day Pista Cookies',
    price: 55.00,
    mrp: 60.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sunfeast-moments',
    name: 'Sunfeast Moments',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Sunfeast',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'parle-g-happy',
    name: 'Parle-G Happy Happy',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'britannia-nutri-choice',
    name: 'Britannia Nutri Choice 5 Grain',
    price: 50.00,
    mrp: 55.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sunfeast-bounce',
    name: 'Sunfeast Bounce',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Sunfeast',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'parle-krackjack-sweet',
    name: 'Parle Krackjack Sweet & Salty',
    price: 12.00,
    mrp: 15.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Parle',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: 'britannia-good-day-chocolate',
    name: 'Good Day Chocolate Cookies',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '100g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'maggi-noodles',
    name: 'Maggi 2-Minute Masala Noodles',
    price: 14.00,
    mrp: 16.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/884600/pexels-photo-884600.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '70g pack',
    brand: 'Maggi',
    offers: ['2 Offers'],
    margin: 2.00,
    inStock: true,
  },
  {
    id: 'almonds-premium',
    name: 'Premium California Almonds',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '500g pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'cashews-roasted',
    name: 'Roasted Cashew Nuts',
    price: 380.00,
    mrp: 420.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '250g pack',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'cornflakes-kelloggs',
    name: 'Kelloggs Corn Flakes',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/5946071/pexels-photo-5946071.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'packagedfoods',
    description: '475g pack',
    brand: 'Kelloggs',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },

  // Home Care Products
  {
    id: 'surf-excel',
    name: 'Surf Excel Easy Wash Detergent Powder',
    price: 85.00,
    mrp: 100.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '1kg pack',
    brand: 'Surf Excel',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'vim-liquid',
    name: 'Vim Liquid Dish Wash',
    price: 125.00,
    mrp: 140.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Vim',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'harpic-toilet-cleaner',
    name: 'Harpic Powerplus Toilet Cleaner',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Harpic',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'dettol-antiseptic',
    name: 'Dettol Antiseptic Liquid',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '250ml bottle',
    brand: 'Dettol',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'lizol-floor-cleaner',
    name: 'Lizol Disinfectant Floor Cleaner',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml bottle',
    brand: 'Lizol',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'ariel-detergent',
    name: 'Ariel Matic Front Load Detergent',
    price: 320.00,
    mrp: 360.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '2kg pack',
    brand: 'Ariel',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'colin-glass-cleaner',
    name: 'Colin Glass & Surface Cleaner',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'homecare',
    description: '500ml spray',
    brand: 'Colin',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },

  // Beverages
  {
    id: 'bournvita',
    name: 'Cadbury Bournvita Health Drink',
    price: 280.00,
    mrp: 320.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '500g jar',
    brand: 'Cadbury',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'tata-gold',
    name: 'Tata Gold Tea',
    price: 165.00,
    mrp: 180.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Tata',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'nescafe-classic',
    name: 'Nescafe Classic Instant Coffee',
    price: 220.00,
    mrp: 250.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '200g jar',
    brand: 'Nescafe',
    offers: ['Best Price'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'red-label-tea',
    name: 'Red Label Natural Care Tea',
    price: 140.00,
    mrp: 155.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '250g pack',
    brand: 'Red Label',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'horlicks-classic',
    name: 'Horlicks Health & Nutrition Drink',
    price: 350.00,
    mrp: 390.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '500g jar',
    brand: 'Horlicks',
    offers: ['Best Price'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'real-juice',
    name: 'Real Mixed Fruit Juice',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '1L pack',
    brand: 'Real',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'coca-cola',
    name: 'Coca Cola Soft Drink',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'beverages',
    description: '600ml bottle',
    brand: 'Coca Cola',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },

  // Personal Care
  {
    id: 'clinic-plus',
    name: 'Clinic Plus Shampoo',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '340ml bottle',
    brand: 'Clinic Plus',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'ponds-cream',
    name: 'Ponds Light Moisturizer',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100ml jar',
    brand: 'Ponds',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'colgate-toothpaste',
    name: 'Colgate Total Advanced Health',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '140g tube',
    brand: 'Colgate',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'head-shoulders',
    name: 'Head & Shoulders Anti-Dandruff Shampoo',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '340ml bottle',
    brand: 'Head & Shoulders',
    offers: ['Offer Applicable'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'dove-soap',
    name: 'Dove Beauty Bar Soap',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '125g bar',
    brand: 'Dove',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'nivea-cream',
    name: 'Nivea Soft Light Moisturizer',
    price: 140.00,
    mrp: 160.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200ml tube',
    brand: 'Nivea',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'listerine-mouthwash',
    name: 'Listerine Cool Mint Mouthwash',
    price: 165.00,
    mrp: 185.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '250ml bottle',
    brand: 'Listerine',
    offers: ['Offer Applicable'],
    margin: 20.00,
    inStock: true,
  },

  // Rice, Atta & Dals
  {
    id: 'india-gate-basmati',
    name: 'India Gate Basmati Rice',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '5kg pack',
    brand: 'India Gate',
    offers: ['Best Price'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'aashirvaad-atta',
    name: 'Aashirvaad Whole Wheat Atta',
    price: 280.00,
    mrp: 310.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '5kg pack',
    brand: 'Aashirvaad',
    offers: ['2 Offers'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'toor-dal',
    name: 'Premium Toor Dal',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'moong-dal',
    name: 'Yellow Moong Dal',
    price: 110.00,
    mrp: 125.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal Premium Quality',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'rajma-red',
    name: 'Red Rajma Kidney Beans',
    price: 140.00,
    mrp: 160.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1392773/pexels-photo-1392773.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },

  // Oil, Sugar & Masalas
  {
    id: 'fortune-sunflower-oil',
    name: 'Fortune Sunflower Oil',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Fortune',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'tata-salt',
    name: 'Tata Salt Iodized',
    price: 22.00,
    mrp: 25.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Tata',
    offers: ['Offer Applicable'],
    margin: 3.00,
    inStock: true,
  },
  {
    id: 'sugar-white',
    name: 'Premium White Sugar',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'mdh-garam-masala',
    name: 'MDH Garam Masala',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'MDH',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'everest-turmeric',
    name: 'Everest Turmeric Powder',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '200g pack',
    brand: 'Everest',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'ghee-amul',
    name: 'Amul Pure Ghee',
    price: 520.00,
    mrp: 580.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L tin',
    brand: 'Amul',
    offers: ['Best Price'],
    margin: 60.00,
    inStock: true,
  },

  // Dairy, Fresh & Frozen
  {
    id: 'amul-milk',
    name: 'Amul Taza Fresh Milk',
    price: 28.00,
    mrp: 30.00,
    discount: 7,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500ml pack',
    brand: 'Amul',
    offers: ['Best Price'],
    margin: 2.00,
    inStock: true,
  },
  {
    id: 'amul-butter',
    name: 'Amul Salted Butter',
    price: 55.00,
    mrp: 60.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '100g pack',
    brand: 'Amul',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'britannia-cheese',
    name: 'Britannia Cheese Slices',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '200g pack',
    brand: 'Britannia',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'nestle-yogurt',
    name: 'Nestle A+ Greek Yogurt',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '400g cup',
    brand: 'Nestle',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'frozen-peas',
    name: 'Frozen Green Peas',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'paneer-fresh',
    name: 'Fresh Paneer Cottage Cheese',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '200g pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },

  // Luggage & Apparel
  {
    id: 'vip-trolley-bag',
    name: 'VIP Trolley Travel Bag',
    price: 2800.00,
    mrp: 3200.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '65cm hard case',
    brand: 'VIP',
    offers: ['Best Price'],
    margin: 400.00,
    inStock: true,
  },
  {
    id: 'american-tourister',
    name: 'American Tourister Backpack',
    price: 1800.00,
    mrp: 2000.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '30L capacity',
    brand: 'American Tourister',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'cotton-tshirt',
    name: 'Premium Cotton T-Shirt',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Size M, L, XL',
    brand: 'Premium',
    offers: ['Offer Applicable'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'formal-shirt',
    name: 'Formal Cotton Shirt',
    price: 850.00,
    mrp: 950.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Size M, L, XL',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
  },
  {
    id: 'sports-shoes',
    name: 'Sports Running Shoes',
    price: 1200.00,
    mrp: 1400.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Size 7-11',
    brand: 'Sports',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'leather-wallet',
    name: 'Genuine Leather Wallet',
    price: 650.00,
    mrp: 750.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Brown/Black',
    brand: 'Premium',
    offers: ['Best Price'],
    margin: 100.00,
    inStock: true,
  },

  // Oil, Sugar & Masalas
  {
    id: 'fortune-rice-bran',
    name: 'Fortune Rice Bran Oil',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Fortune',
    offers: ['Offer Applicable'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'saffola-gold',
    name: 'Saffola Gold Refined Oil',
    price: 150.00,
    mrp: 170.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Saffola',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'dhara-mustard',
    name: 'Dhara Mustard Oil',
    price: 180.00,
    mrp: 200.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1L bottle',
    brand: 'Dhara',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'patanjali-ghee',
    name: 'Patanjali Cow Ghee',
    price: 450.00,
    mrp: 500.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Patanjali',
    offers: ['Offer Applicable'],
    margin: 50.00,
    inStock: true,
  },
  {
    id: 'amul-ghee',
    name: 'Amul Pure Ghee',
    price: 520.00,
    mrp: 580.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Amul',
    offers: ['2 Offers'],
    margin: 60.00,
    inStock: true,
  },
  {
    id: 'tata-salt',
    name: 'Tata Salt Iodized',
    price: 20.00,
    mrp: 25.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Tata',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sugar-refined',
    name: 'Refined Sugar',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'mdh-garam-masala',
    name: 'MDH Garam Masala',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'MDH',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'everest-chicken-masala',
    name: 'Everest Chicken Masala',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Everest',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'catch-chat-masala',
    name: 'Catch Chat Masala',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Catch',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'patanjali-turmeric',
    name: 'Patanjali Turmeric Powder',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '200g pack',
    brand: 'Patanjali',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'red-chilli-powder',
    name: 'Red Chilli Powder',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'coriander-powder',
    name: 'Coriander Powder',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'cumin-powder',
    name: 'Cumin Powder',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'black-pepper',
    name: 'Black Pepper Powder',
    price: 60.00,
    mrp: 70.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'cardamom-powder',
    name: 'Cardamom Powder',
    price: 80.00,
    mrp: 90.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'cinnamon-powder',
    name: 'Cinnamon Powder',
    price: 70.00,
    mrp: 80.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'nutmeg-powder',
    name: 'Nutmeg Powder',
    price: 90.00,
    mrp: 100.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'clove-powder',
    name: 'Clove Powder',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'bay-leaves',
    name: 'Bay Leaves',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '50g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'fenugreek-powder',
    name: 'Fenugreek Powder',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'oilsugar',
    description: '100g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  ...additionalProducts,
  ...moreProducts,
  ...remainingProducts,
  ...electronicsProducts,
];

export const brands = [
  { name: 'Surf Excel', logo: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Colgate', logo: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Dettol', logo: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Harpic', logo: 'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Parle', logo: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Amul', logo: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Tata', logo: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=100' },
  { name: 'Britannia', logo: 'https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=100' },
];