import { Product } from '@/types';

export const moreProducts: Product[] = [
  // Personal Care (25 items)
  {
    id: 'colgate-toothpaste',
    name: 'Colgate Strong Teeth Toothpaste',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200g tube',
    brand: 'Colgate',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'pepsodent-toothpaste',
    name: 'Pepsodent Complete Protection',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200g tube',
    brand: 'Pepsodent',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'closeup-toothpaste',
    name: 'Close Up Fresh Gel',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200g tube',
    brand: 'Close Up',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'sensoform-toothbrush',
    name: 'Sensoform Soft Toothbrush',
    price: 25.00,
    mrp: 30.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: 'Pack of 2',
    brand: 'Sensoform',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'colgate-toothbrush',
    name: 'Colgate Slim Soft Toothbrush',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: 'Pack of 2',
    brand: 'Colgate',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'listerine-mouthwash',
    name: 'Listerine Cool Mint Mouthwash',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '250ml bottle',
    brand: 'Listerine',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'colgate-mouthwash',
    name: 'Colgate Plax Mouthwash',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '250ml bottle',
    brand: 'Colgate',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'dental-floss',
    name: 'Oral B Dental Floss',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '50m roll',
    brand: 'Oral B',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'head-shoulders-shampoo',
    name: 'Head & Shoulders Anti-Dandruff',
    price: 95.00,
    mrp: 105.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'Head & Shoulders',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'pantene-shampoo',
    name: 'Pantene Pro-V Shampoo',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'Pantene',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'sunsilk-shampoo',
    name: 'Sunsilk Hair Care Shampoo',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'Sunsilk',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'dove-shampoo',
    name: 'Dove Hair Care Shampoo',
    price: 90.00,
    mrp: 100.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'Dove',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'tresemme-shampoo',
    name: 'TRESemme Hair Care Shampoo',
    price: 110.00,
    mrp: 125.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'TRESemme',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'loreal-shampoo',
    name: 'L\'Oreal Paris Hair Care',
    price: 120.00,
    mrp: 135.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'L\'Oreal',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'garnier-shampoo',
    name: 'Garnier Fructis Shampoo',
    price: 80.00,
    mrp: 90.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'Garnier',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'clinic-plus-shampoo',
    name: 'Clinic Plus Shampoo',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '170ml bottle',
    brand: 'Clinic Plus',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'parachute-coconut-oil',
    name: 'Parachute Coconut Oil',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200ml bottle',
    brand: 'Parachute',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'dabur-amla-oil',
    name: 'Dabur Amla Hair Oil',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '200ml bottle',
    brand: 'Dabur',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'himani-boroplus',
    name: 'Himani Boroplus Cream',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '50g tube',
    brand: 'Himani',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'ponds-cold-cream',
    name: 'Ponds Cold Cream',
    price: 40.00,
    mrp: 45.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '50g jar',
    brand: 'Ponds',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'vaseline-petroleum-jelly',
    name: 'Vaseline Petroleum Jelly',
    price: 30.00,
    mrp: 35.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100g jar',
    brand: 'Vaseline',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'nivea-cream',
    name: 'Nivea Soft Cream',
    price: 50.00,
    mrp: 60.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100ml tube',
    brand: 'Nivea',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'lakme-lipstick',
    name: 'Lakme Absolute Lipstick',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '3.6g tube',
    brand: 'Lakme',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'maybelline-mascara',
    name: 'Maybelline Volume Express Mascara',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '9.5ml tube',
    brand: 'Maybelline',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'loreal-foundation',
    name: 'L\'Oreal Paris Foundation',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '30ml bottle',
    brand: 'L\'Oreal',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'ponds-face-wash',
    name: 'Ponds Face Wash',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100g tube',
    brand: 'Ponds',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'garnier-face-wash',
    name: 'Garnier Skin Naturals Face Wash',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100g tube',
    brand: 'Garnier',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'clean-clear-face-wash',
    name: 'Clean & Clear Face Wash',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100g tube',
    brand: 'Clean & Clear',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'neutrogena-face-wash',
    name: 'Neutrogena Deep Clean Face Wash',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '100g tube',
    brand: 'Neutrogena',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'nivea-deodorant',
    name: 'Nivea Men Deodorant',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '150ml spray',
    brand: 'Nivea',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'axe-deodorant',
    name: 'Axe Dark Temptation Deodorant',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '150ml spray',
    brand: 'Axe',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'park-avenue-deodorant',
    name: 'Park Avenue Deodorant',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '150ml spray',
    brand: 'Park Avenue',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fogg-deodorant',
    name: 'Fogg Scent Deodorant',
    price: 50.00,
    mrp: 60.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/3735746/pexels-photo-3735746.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'personalcare',
    description: '150ml spray',
    brand: 'Fogg',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },

  // Rice, Atta & Dals (25 items)
  {
    id: 'basmati-rice',
    name: 'India Gate Basmati Rice',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'India Gate',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'sona-masoori-rice',
    name: 'Sona Masoori Rice',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'red-rice',
    name: 'Red Rice',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'atta-wheat-flour',
    name: 'Aashirvaad Atta Wheat Flour',
    price: 45.00,
    mrp: 50.00,
    discount: 10,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Aashirvaad',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'pillsbury-atta',
    name: 'Pillsbury Chakki Fresh Atta',
    price: 50.00,
    mrp: 55.00,
    discount: 9,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Pillsbury',
    offers: ['Best Price'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'tata-sampann-atta',
    name: 'Tata Sampann Wheat Atta',
    price: 55.00,
    mrp: 60.00,
    discount: 8,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Tata Sampann',
    offers: ['2 Offers'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'organic-atta',
    name: 'Organic Wheat Atta',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Organic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'multigrain-atta',
    name: 'Multigrain Atta',
    price: 70.00,
    mrp: 80.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'toor-dal',
    name: 'Toor Dal (Pigeon Peas)',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'moong-dal',
    name: 'Moong Dal (Green Gram)',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'masoor-dal',
    name: 'Masoor Dal (Red Lentils)',
    price: 65.00,
    mrp: 75.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'urad-dal',
    name: 'Urad Dal (Black Gram)',
    price: 80.00,
    mrp: 90.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal (Bengal Gram)',
    price: 70.00,
    mrp: 80.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'rajma-kidney-beans',
    name: 'Rajma (Kidney Beans)',
    price: 60.00,
    mrp: 70.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'chickpeas',
    name: 'Chickpeas (Kabuli Chana)',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'black-eyed-peas',
    name: 'Black Eyed Peas (Lobia)',
    price: 50.00,
    mrp: 60.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'green-peas',
    name: 'Green Peas',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    price: 120.00,
    mrp: 140.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'oats',
    name: 'Quaker Oats',
    price: 85.00,
    mrp: 95.00,
    discount: 11,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '1kg pack',
    brand: 'Quaker',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'muesli',
    name: 'Kellogg\'s Muesli',
    price: 95.00,
    mrp: 110.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Kellogg\'s',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'corn-flakes',
    name: 'Kellogg\'s Corn Flakes',
    price: 75.00,
    mrp: 85.00,
    discount: 12,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Kellogg\'s',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'wheat-bran',
    name: 'Wheat Bran',
    price: 40.00,
    mrp: 50.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'ragi-flour',
    name: 'Ragi Flour (Finger Millet)',
    price: 60.00,
    mrp: 70.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'jowar-flour',
    name: 'Jowar Flour (Sorghum)',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'bajra-flour',
    name: 'Bajra Flour (Pearl Millet)',
    price: 50.00,
    mrp: 60.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'amaranth-seeds',
    name: 'Amaranth Seeds (Rajgira)',
    price: 80.00,
    mrp: 95.00,
    discount: 16,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '500g pack',
    brand: 'Generic',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'chia-seeds',
    name: 'Chia Seeds',
    price: 150.00,
    mrp: 180.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '250g pack',
    brand: 'Generic',
    offers: ['Offer Applicable'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'flax-seeds',
    name: 'Flax Seeds (Alsi)',
    price: 90.00,
    mrp: 110.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'ricedals',
    description: '250g pack',
    brand: 'Generic',
    offers: ['Best Price'],
    margin: 20.00,
    inStock: true,
  },
]; 