import { Product } from '@/types';

export const remainingProducts: Product[] = [
  // Daily Fresh & Frozen (25 items)
  {
    id: 'fresh-tomatoes',
    name: 'Fresh Tomatoes',
    price: 40.00,
    mrp: 50.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-onions',
    name: 'Fresh Onions',
    price: 30.00,
    mrp: 40.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-potatoes',
    name: 'Fresh Potatoes',
    price: 35.00,
    mrp: 45.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-carrots',
    name: 'Fresh Carrots',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-capsicum',
    name: 'Fresh Capsicum',
    price: 60.00,
    mrp: 75.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['2 Offers'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'fresh-cucumber',
    name: 'Fresh Cucumber',
    price: 25.00,
    mrp: 35.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-cabbage',
    name: 'Fresh Cabbage',
    price: 20.00,
    mrp: 30.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-cauliflower',
    name: 'Fresh Cauliflower',
    price: 30.00,
    mrp: 40.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-brinjal',
    name: 'Fresh Brinjal',
    price: 35.00,
    mrp: 45.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-ladyfinger',
    name: 'Fresh Ladyfinger',
    price: 40.00,
    mrp: 50.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-apples',
    name: 'Fresh Apples',
    price: 120.00,
    mrp: 150.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'fresh-bananas',
    name: 'Fresh Bananas',
    price: 60.00,
    mrp: 75.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'fresh-oranges',
    name: 'Fresh Oranges',
    price: 80.00,
    mrp: 100.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['2 Offers'],
    margin: 20.00,
    inStock: true,
  },
  {
    id: 'fresh-mangoes',
    name: 'Fresh Mangoes',
    price: 100.00,
    mrp: 125.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1kg pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 25.00,
    inStock: true,
  },
  {
    id: 'fresh-grapes',
    name: 'Fresh Grapes',
    price: 150.00,
    mrp: 180.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 30.00,
    inStock: true,
  },
  {
    id: 'frozen-peas',
    name: 'Frozen Green Peas',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Frozen',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'frozen-corn',
    name: 'Frozen Sweet Corn',
    price: 50.00,
    mrp: 60.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Frozen',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'frozen-french-fries',
    name: 'Frozen French Fries',
    price: 85.00,
    mrp: 100.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Frozen',
    offers: ['Offer Applicable'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'amul-milk',
    name: 'Amul Full Cream Milk',
    price: 60.00,
    mrp: 70.00,
    discount: 14,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '1L tetra pack',
    brand: 'Amul',
    offers: ['Best Price'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'amul-curd',
    name: 'Amul Masti Dahi',
    price: 35.00,
    mrp: 40.00,
    discount: 13,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '400g cup',
    brand: 'Amul',
    offers: ['Offer Applicable'],
    margin: 5.00,
    inStock: true,
  },
  {
    id: 'amul-butter',
    name: 'Amul Butter',
    price: 55.00,
    mrp: 65.00,
    discount: 15,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '100g pack',
    brand: 'Amul',
    offers: ['2 Offers'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'amul-cheese',
    name: 'Amul Processed Cheese',
    price: 45.00,
    mrp: 55.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '200g pack',
    brand: 'Amul',
    offers: ['Offer Applicable'],
    margin: 10.00,
    inStock: true,
  },
  {
    id: 'fresh-eggs',
    name: 'Fresh Farm Eggs',
    price: 80.00,
    mrp: 95.00,
    discount: 16,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '12 eggs pack',
    brand: 'Fresh',
    offers: ['Best Price'],
    margin: 15.00,
    inStock: true,
  },
  {
    id: 'fresh-chicken',
    name: 'Fresh Chicken Breast',
    price: 180.00,
    mrp: 220.00,
    discount: 18,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['Offer Applicable'],
    margin: 40.00,
    inStock: true,
  },
  {
    id: 'fresh-fish',
    name: 'Fresh Rohu Fish',
    price: 200.00,
    mrp: 250.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1446504/pexels-photo-1446504.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'dailyfresh',
    description: '500g pack',
    brand: 'Fresh',
    offers: ['2 Offers'],
    margin: 50.00,
    inStock: true,
  },

  // Luggage & Apparel (25 items)
  {
    id: 'american-tourister-luggage',
    name: 'American Tourister Luggage',
    price: 2500.00,
    mrp: 3000.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '55cm hard shell',
    brand: 'American Tourister',
    offers: ['2 Offers'],
    margin: 500.00,
    inStock: true,
  },
  {
    id: 'skybags-backpack',
    name: 'Skybags Backpack',
    price: 800.00,
    mrp: 1000.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '20L capacity',
    brand: 'Skybags',
    offers: ['Offer Applicable'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'wildcraft-backpack',
    name: 'Wildcraft Backpack',
    price: 1200.00,
    mrp: 1500.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '25L capacity',
    brand: 'Wildcraft',
    offers: ['Best Price'],
    margin: 300.00,
    inStock: true,
  },
  {
    id: 'puma-tshirt',
    name: 'Puma Men\'s T-Shirt',
    price: 450.00,
    mrp: 600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Cotton blend',
    brand: 'Puma',
    offers: ['Offer Applicable'],
    margin: 150.00,
    inStock: true,
  },
  {
    id: 'adidas-tshirt',
    name: 'Adidas Men\'s T-Shirt',
    price: 500.00,
    mrp: 650.00,
    discount: 23,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Polyester blend',
    brand: 'Adidas',
    offers: ['2 Offers'],
    margin: 150.00,
    inStock: true,
  },
  {
    id: 'nike-tshirt',
    name: 'Nike Men\'s T-Shirt',
    price: 550.00,
    mrp: 700.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Dri-FIT technology',
    brand: 'Nike',
    offers: ['Offer Applicable'],
    margin: 150.00,
    inStock: true,
  },
  {
    id: 'levis-jeans',
    name: 'Levi\'s Men\'s Jeans',
    price: 1200.00,
    mrp: 1500.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Denim fabric',
    brand: 'Levi\'s',
    offers: ['Best Price'],
    margin: 300.00,
    inStock: true,
  },
  {
    id: 'wrangler-jeans',
    name: 'Wrangler Men\'s Jeans',
    price: 1000.00,
    mrp: 1300.00,
    discount: 23,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Comfort fit',
    brand: 'Wrangler',
    offers: ['Offer Applicable'],
    margin: 300.00,
    inStock: true,
  },
  {
    id: 'pepe-jeans',
    name: 'Pepe Jeans Men\'s Jeans',
    price: 1100.00,
    mrp: 1400.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Slim fit',
    brand: 'Pepe Jeans',
    offers: ['2 Offers'],
    margin: 300.00,
    inStock: true,
  },
  {
    id: 'nike-shoes',
    name: 'Nike Air Max Shoes',
    price: 2500.00,
    mrp: 3200.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Running shoes',
    brand: 'Nike',
    offers: ['Offer Applicable'],
    margin: 700.00,
    inStock: true,
  },
  {
    id: 'adidas-shoes',
    name: 'Adidas Ultraboost Shoes',
    price: 2800.00,
    mrp: 3500.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Sports shoes',
    brand: 'Adidas',
    offers: ['Best Price'],
    margin: 700.00,
    inStock: true,
  },
  {
    id: 'puma-shoes',
    name: 'Puma RS-X Shoes',
    price: 2200.00,
    mrp: 2800.00,
    discount: 21,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Casual shoes',
    brand: 'Puma',
    offers: ['Offer Applicable'],
    margin: 600.00,
    inStock: true,
  },
  {
    id: 'reebok-shoes',
    name: 'Reebok Classic Shoes',
    price: 1800.00,
    mrp: 2300.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Retro style',
    brand: 'Reebok',
    offers: ['2 Offers'],
    margin: 500.00,
    inStock: true,
  },
  {
    id: 'casio-watch',
    name: 'Casio G-Shock Watch',
    price: 1500.00,
    mrp: 2000.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Digital watch',
    brand: 'Casio',
    offers: ['Offer Applicable'],
    margin: 500.00,
    inStock: true,
  },
  {
    id: 'titan-watch',
    name: 'Titan Analog Watch',
    price: 1200.00,
    mrp: 1600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Leather strap',
    brand: 'Titan',
    offers: ['Best Price'],
    margin: 400.00,
    inStock: true,
  },
  {
    id: 'fastrack-watch',
    name: 'Fastrack Digital Watch',
    price: 800.00,
    mrp: 1100.00,
    discount: 27,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Sports watch',
    brand: 'Fastrack',
    offers: ['Offer Applicable'],
    margin: 300.00,
    inStock: true,
  },
  {
    id: 'sonata-watch',
    name: 'Sonata Analog Watch',
    price: 600.00,
    mrp: 800.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Classic design',
    brand: 'Sonata',
    offers: ['2 Offers'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'ray-ban-sunglasses',
    name: 'Ray-Ban Aviator Sunglasses',
    price: 3500.00,
    mrp: 4500.00,
    discount: 22,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Polarized lenses',
    brand: 'Ray-Ban',
    offers: ['Offer Applicable'],
    margin: 1000.00,
    inStock: true,
  },
  {
    id: 'vincent-chase-sunglasses',
    name: 'Vincent Chase Sunglasses',
    price: 800.00,
    mrp: 1200.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'UV protection',
    brand: 'Vincent Chase',
    offers: ['Best Price'],
    margin: 400.00,
    inStock: true,
  },
  {
    id: 'john-jacobs-sunglasses',
    name: 'John Jacobs Sunglasses',
    price: 1200.00,
    mrp: 1600.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Round frame',
    brand: 'John Jacobs',
    offers: ['Offer Applicable'],
    margin: 400.00,
    inStock: true,
  },
  {
    id: 'tanishq-necklace',
    name: 'Tanishq Gold Necklace',
    price: 25000.00,
    mrp: 30000.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: '22K gold',
    brand: 'Tanishq',
    offers: ['2 Offers'],
    margin: 5000.00,
    inStock: true,
  },
  {
    id: 'kalyan-jewellers-ring',
    name: 'Kalyan Jewellers Diamond Ring',
    price: 15000.00,
    mrp: 18000.00,
    discount: 17,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Solitaire ring',
    brand: 'Kalyan Jewellers',
    offers: ['Offer Applicable'],
    margin: 3000.00,
    inStock: true,
  },
  {
    id: 'malabar-gold-earrings',
    name: 'Malabar Gold Earrings',
    price: 8000.00,
    mrp: 10000.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Traditional design',
    brand: 'Malabar Gold',
    offers: ['Best Price'],
    margin: 2000.00,
    inStock: true,
  },
  {
    id: 'lifestyle-belt',
    name: 'Lifestyle Leather Belt',
    price: 400.00,
    mrp: 600.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Genuine leather',
    brand: 'Lifestyle',
    offers: ['Offer Applicable'],
    margin: 200.00,
    inStock: true,
  },
  {
    id: 'puma-wallet',
    name: 'Puma Leather Wallet',
    price: 300.00,
    mrp: 450.00,
    discount: 33,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Multiple card slots',
    brand: 'Puma',
    offers: ['2 Offers'],
    margin: 150.00,
    inStock: true,
  },
  {
    id: 'adidas-cap',
    name: 'Adidas Baseball Cap',
    price: 250.00,
    mrp: 350.00,
    discount: 29,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Adjustable fit',
    brand: 'Adidas',
    offers: ['Offer Applicable'],
    margin: 100.00,
    inStock: true,
  },
  {
    id: 'nike-socks',
    name: 'Nike Athletic Socks',
    price: 150.00,
    mrp: 200.00,
    discount: 25,
    image: 'https://images.pexels.com/photos/1553062/pexels-photo-1553062.jpeg?auto=compress&cs=tinysrgb&w=300',
    category: 'luggageapparel',
    description: 'Pack of 3',
    brand: 'Nike',
    offers: ['Best Price'],
    margin: 50.00,
    inStock: true,
  },
]; 